# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starship',
            name='model',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starship',
            name='name',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
